---
title: "ThaiGov's 2022 Budget"
output: github_document
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

```{r, include = FALSE}
library(targets)
```

```{r, include = FALSE}
tar_unscript()
```

<blockquote class="twitter-tweet"><p lang="th" dir="ltr">[ Excel <a href="https://twitter.com/hashtag/%E0%B8%87%E0%B8%9A65?src=hash&amp;ref_src=twsrc%5Etfw">#งบ65</a> สำเร็จแล้ว! ใช้ไปเลยชั่วลูกชั่วหลาน ]<br><br>ดาวน์โหลด: <a href="https://t.co/PuhflF8DEF">https://t.co/PuhflF8DEF</a><br><br>เราจะทำตามสัญญา ขอเวลาอีกไม่นาน ...<br><br>หลัง งปม. วาระ 1 ผ่านสภา พวกเราเคยให้สัญญากับทุกท่านไว้ว่า จะรวมพลังสาย dev เพื่อแปลงงบ pdf สู่ machine-readable แบบทำครั้งเดียว ใช้ได้ชั่วลูกชั่วหลาน <a href="https://t.co/b0pWMF3jDc">pic.twitter.com/b0pWMF3jDc</a></p>&mdash; ณัฐพงษ์ เรืองปัญญาวุฒิ (เท้ง) (@teng_mfp) <a href="https://twitter.com/teng_mfp/status/1417872910383865859?ref_src=twsrc%5Etfw">July 21, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

```{targets, tar_globals = TRUE}
options(tidyverse.quiet = TRUE)
tar_option_set(packages = c("dplyr", "ggplot2", "googlesheets4", "tidyr", "skimr", "magrittr", "googleLanguageR"))
```

# Targets

```{targets budget_raw, tar_simple = TRUE}
read_sheet("https://docs.google.com/spreadsheets/d/1yyWXSTbq3CD_gNxks-krcSBzbszv3c_2Nq54lckoQ24/edit#gid=1625073248")
```

```{targets data-prep}
list(
  tar_target(budget, budget_raw %>% janitor::clean_names()),
  tar_target(unique_sentences, {
    budget %>%
      select(
        ministry,
        budgetary_unit,
        budget_plan,
        output,
        project,
        starts_with("category"),
        item_description
      ) %>% {
        as.character(unique(unlist(.)))
      }
  }),
  tar_target(sampled_sentences,
             sample(unique_sentences, 5))
)
```

```{targets chunks_of_unique_sentences, tar_simple = TRUE}
unique_sentences %>%
  sample(size = 20, replace = FALSE) %>%
  split(., ceiling(seq_along(.) / 5))
```

```{targets translation}
list(
  tar_target(translated_sentences, {
    gl_translate(sampled_sentences, target = "en")
  }),
  tar_target(translated_ministry, {
    budget$ministry %>%
      unique() %>%
      gl_translate(target = "en")
  })
)
```

```{targets translate-by-chunk} 
list(
  tar_target(
    translated_chucks, 
    gl_translate(chunks_of_unique_sentences[[1]], target = "en"), 
    pattern = map(chunks_of_unique_sentences), 
    iteration = "list"
  )
)
```

```{targets translated_budget, tar_simple = TRUE}
translated_ministry %>%
  mutate(translatedText = tools::toTitleCase(translatedText)) %>%
  merge(budget, ., by.x = "ministry", by.y = "text") %>%
  select(-detectedSourceLanguage) %>%
  rename(ministry_en = "translatedText")
```

# Pipeline

```{r}
tar_make()
```

```{r visnetwork}
tar_visnetwork()
```

# Output

```{r, message=FALSE}
library(dplyr)
library(skimr)
library(ggplot2)
library(kableExtra)
library(stringr)
library(forcats)
library(scales)
```

```{r}
tar_read(budget) %>%
  skimr::skim()
```

```{r}
tar_read(unique_sentences) %>%
  head()
```

```{r}
tar_read(translated_sentences) %>%
  dplyr::select(-detectedSourceLanguage) %>%
  kableExtra::kbl()
```

```{r total-budget-by-ministry, fig.height=10, dpi=300}
tar_read(budget_en) %>%
  mutate(ministry_en = ifelse(grepl("Ministry of Higher Education", ministry_en) == TRUE, 
                               "Ministry of Higher Education, Science, Research and Innovation",
                               ministry_en)) %>%
  group_by(ministry_en) %>%
  summarise(amount = sum(amount, na.rm = TRUE)) %>%
  ggplot(data = ., aes(
    x = amount,
    y = forcats::fct_reorder(stringr::str_wrap(ministry_en, 40), amount)
  )) +
  geom_col() +
  scale_x_continuous(labels = unit_format(unit = "M", scale = 1e-6, big.mark = ",")) +
  scale_y_discrete(expand = c(0, 0)) +
  theme_bw(base_size = 12) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x = "Amount in Million Thai Bahts", y = "Ministry")
```

